services:
  api:
    build: .
    environment:
      - API_ADDR=:8080
      - KEYDB_ADDR=keydb:6379
    depends_on:
      - keydb
    ports:
      - "28080:8080"
  keydb:
    image: eqalpha/keydb:latest
    command: >-
      --appendonly yes
      --save 300 10
    volumes:
      - keydb-data:/data

volumes:
  keydb-data:
    driver: local

networks:
  public:
    enable_ipv6: false
  private:
    enable_ipv6: false
    internal: true
